COLUMN_MAP = {
    # Internal Name   : [Standard Excel Name, Other Possible Names...]
    'Employee_ID'       : ['Employee ID', 'Employee Number', 'Emp ID', 'ID', 'Emp No', 'Employee No', 'Emp_Number', 'EmpID', 'EmployeeID'],
    'Employee_Name'     : ['Employee Name', 'Name'],
    'Employee_Email'    : ['Employee Email', 'Email', 'Email ID'],
    'Department'        : ['Department'],
    'Designation'       : ['Designation'],
    'Location'          : ['Location', 'Address', 'City', 'State', 'Place', 'Work Location', 'Work_Location'],
    'Date_of_Joining'   : ['Date of Joining', 'DOJ', 'Joining Date', 'Join Date', 'Date Joined', 'Date_Of_Joining', 'DateJoined', 'Date_of_Joining'],
    'Bank_Name'         : ['Bank Name', 'Bank_Name'],
    'Bank_Account_No'   : ['Bank Account No', 'Account No', 'Account Number', 'Bank Account Number', 'Bank_Account_No', 'BankAccountNo', 'BankAccountNumber'],
    'PAN_Number'        : ['PAN Number', 'PAN', 'PAN No', 'PAN_Number', 'PANNo'],
    'PF_Account_Number' : ['PF Account Number', 'PF No', 'PF Number', 'Provident Fund Number', 'PF_Account_Number', 'PFAccountNumber'],
    'ESI_Number'        : ['ESI Number', 'ESI No', 'ESI', 'ESI_Number', 'ESINumber'],
    'UAN_Number'        : ['UAN Number', 'UAN', 'UAN No', 'UAN_Number', 'UANNumber'],  
    'Period'            : ['Period', 'Salary Month', 'Month', 'Salary Period'],
    'Days_Worked'       : ['Days Worked', 'No. of Days Worked', 'Days_Worked'],   
    'LOP_Days'          : ['LOP Days', 'Loss of Pay Days', 'LOP', 'LOP_Days'],
    'Gross_Salary'      : ['Gross Salary', 'Gross'],
    'Income_Tax'        : ['Income Tax', 'IT Deduction'],
    'Basic'             : ['Basic', 'Basic Salary'],
    'HRA'               : ['HRA', 'House Rent Allowance'],
    'Special_Allowance' : ['Special Allowance', 'Allowance', 'Special Allowances', 'Allowances'],
    'EPF'               : ['EPF', 'Provident Fund', 'PF Deduction'],
}